# Clear cached module icon backgrounds so catppuccin rebuilds them
set -gu @catppuccin_status_session_icon_bg
set -gu @catppuccin_status_directory_icon_bg
set -gu @catppuccin_status_date_time_icon_bg

# Rebuild catppuccin
source-file ~/.local/share/tmux/plugins/tmux/catppuccin_tmux.conf

# Reset status bar
set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
