# Mauve: catppuccin default, purple active window
set -g @catppuccin_window_current_number_color "#{@thm_mauve}"
set -g @catppuccin_window_number_color "#{@thm_surface_2}"
set -g @catppuccin_session_color "#{?client_prefix,#{E:@thm_red},#{E:@thm_green}}"
set -g @catppuccin_directory_color "#{E:@thm_rosewater}"
set -g @catppuccin_date_time_color "#{E:@thm_sapphire}"
source-file ~/.config/tmux/themes/_apply.conf
display-message "  Mauve"
