# Neon: vibrant, high energy
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_number_color "#{@thm_overlay_0}"
set -g @catppuccin_session_color "#{?client_prefix,#{E:@thm_red},#{E:@thm_pink}}"
set -g @catppuccin_directory_color "#{E:@thm_yellow}"
set -g @catppuccin_date_time_color "#{E:@thm_sky}"
source-file ~/.config/tmux/themes/_apply.conf
display-message "  Neon"
