# Sakura: pink/purple, soft and elegant
set -g @catppuccin_window_current_number_color "#{@thm_pink}"
set -g @catppuccin_window_number_color "#{@thm_surface_2}"
set -g @catppuccin_session_color "#{?client_prefix,#{E:@thm_red},#{E:@thm_mauve}}"
set -g @catppuccin_directory_color "#{E:@thm_flamingo}"
set -g @catppuccin_date_time_color "#{E:@thm_lavender}"
source-file ~/.config/tmux/themes/_apply.conf
display-message "  Sakura"
